### PR TITLE
Added grouping and sorting feature for Card and Path columns

### PR DESCRIPTION
**Pull request by ashuchow**
I have consolidated all features mentioned in Issue 9 (https://github.com/coronasafe/metabase_manager/issues/9) except for the sorting status feature. That is, currently the branch from which the pull request has been set up has the following features:
1. Sorting by ascending and descending for Card and Path Columns
2. Collapsible and Expandable sections for cards that fall under sub collections
3. Collapsible and Expandable sections for Collections based on instance/Destination

### CODE REVIEW

**Comment by ashuchow** [comment]
Completed incorporating the sorting by status feature. Should be good to review in entirety now. @gigincg @Ashesh3

**Review by Ashesh3 — CHANGES_REQUESTED** [review]
**Functionality working fine:**

- Grouping works fine - Cards are grouped within the collection which in turn are grouped as per source hostname.
- Expanding / Collapsing the groups work fine
- Sorting by path works fine
- Sorting by card name works fine
- Sorting is applied to the groups individually
- Select All correctly selects all entries within all groups and subgroups

**Functionality needing attention:**
- Unable to sort status in descending order; clicking it only toggles between no sorting and Ascending.
- Clicking the "status" heading to sort it while there's already a sort applied on card name / path does not remove the existing sort, instead it tries to sort by both fields, this is not the case with card name and path filters (i.e if you apply one of them, the other one is removed correctly)
- Let's also have a button to expand ALL / collapse ALL groups + subgroups with a single button press

**Design Changes (post functionality fixes):**
After the above issues are addressed, let's touch on the design once since the current design does not match well with the existing design. 

image


Recommended Design components (To be taken look at after the above functionality issues are addressed):
- Accordion for collapsible collection names (Reference: https://nextui.org/docs/components/accordion)
	- There should be a clear distinction between accordion for a host and collection. i.e It should be clear by itself that if we are expanding a host or a collection within a host
	

image

- Recommended to use a badge to show the count of card within a group (Reference: https://nextui.org/docs/components/badge)

image


Or use a subtext to show the count + selected count

image

- Improve the icon for sorting - to better indicate the sort direction (Reference: https://nextui.org/docs/components/table#sorting-rows)
msedge_JDgXgaV7GV

Overall Looks good to me, basic functionality works, just need a few fixes and design improvements then good to merge.

**Review by Ashesh3 — CHANGES_REQUESTED** [review]
Apart from the above changes, remove the changes to `package.json` and `package-lock.json` since you have not added any new packages as of yet, so these two files should remain unchanged - Remove them from this PR. (Feel free to add them if and once you have added new npm packages)

**Comment by ashuchow** [comment]
@Ashesh3 @gigincg I've added the functionalities as requested. Please have a look and let me know if they're good and I will start implementing the design improvements!

**Comment by Ashesh3** [comment]
Great improvement! All the functionality seems to be working now. Let's proceed with the design changes to finalize it.

**Comment by Ashesh3** [comment]
Closing as these changes are consolidated into #15

**Pull request closed without merging**
